### ISSUE TITLE
Failed to load the symfony-commands package

### ISSUE THREAD

**Issue by azatyan** [twifty/atom-symfony-commands#1] opened 2018-02-07 03:52 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [symfony-commands](https://github.com/twifty/atom-symfony-commands) package 0.1.4

### Stack Trace

Failed to load the symfony-commands package

```
At Cannot read property 'loadAddon' of undefined

TypeError: Cannot read property 'loadAddon' of undefined
    at /packages/symfony-commands/lib/symfony-console-view.js:14:1)
    at /packages/symfony-commands/lib/symfony-console-view.js:16:33)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/symfony-commands/lib/symfony-commands.js:4:61)
    at /packages/symfony-commands/lib/symfony-commands.js:59:2)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -3:35.9.0 tree-view:reveal-active-file (input.hidden-input)
     -1:12.8.0 core:backspace (input.hidden-input)
     -1:02.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-symfony 1.2.0 
atom-symfony-snippets 0.2.1 
atom-symfony2 0.3.0 
symfony-commands 0.1.4 
symfony-snippets 0.3.0 
symfony-trans-replacer 2.0.0 
teletype 0.7.0 
```

**Comment by chrillep** [comment] 2018-03-03 12:15
any update?

**Comment by twifty** [comment] 2018-03-04 01:24
Sorry guys, I've been tied up with work the last few weeks.

After a quick look I'm unable to reproduce the problem. Saying that though, I don't have access to a Mac.

Does the problem persist on Atom 1.25?

**Comment by twifty** [comment] 2018-03-05 21:25
Fixed in https://github.com/twifty/atom-symfony-commands/releases/tag/v0.1.5

**Closed** 2018-03-06 02:47 UTC
